'use strict';

export const ActionTypes = {
  CONNECTING: 'CONNECTING',
  CONNECT: 'CONNECT',
  DISCONNECTING: 'DISCONNECTING',
  DISCONNECT: 'DISCONNECT',
  RECEIVE_MESSAGE: 'RECEIVE_MESSAGE',
  SEND_COMMAND: 'SEND_COMMAND',
};
